name: Vite Github Pages Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master", "main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  API_BASE_URL: ${{ secrets.API_BASE_URL }}

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Clean node_modules and package-lock.json
      run: | 
        rm -rf node_modules package-lock.json

    - name: Install dependencies
      run: npm install

    - name: Vite Github Pages Deployer
      uses: skywarth/vite-github-pages-deployer@master
      with:
        build_path: "./dist"
      env:
        VITE_APP_BASE_URL: "/${{ github.event.repository.name }}/"
        id: deploy_to_pages
